### ISSUE TITLE
分钟线行情数据能用 Golang 拉取吗？

### ISSUE THREAD

**Issue by uiosun** [yushikuann/go-tushare-sdk#1]
看了官方文档，通用行情接口说“没有直接实现”，分钟线行情似乎比较复杂？

请教一下是否能实现？

> 集成接口，在SDK层做了一些逻辑处理，目前暂时没法用http的方式调取通用行情接口。用户可以访问Tushare的Github，查看源代码完成类似功能。
> https://tushare.pro/document/2?doc_id=109

**Comment by yushikuann** [comment]
sdk 底层必然使用的也是http请求，sdk封装应该只是做了一些限制操作



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: UioSun ***@***.***&gt;
发送时间: 2024年5月8日 17:50
收件人: yushikuann/go-tushare-sdk ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yushikuann/go-tushare-sdk] 分钟线行情数据能用 Golang 拉取吗？ (Issue #1)





 
看了官方文档，通用行情接口说“没有直接实现”，分钟线行情似乎比较复杂？
 
请教一下是否能实现？
  
集成接口，在SDK层做了一些逻辑处理，目前暂时没法用http的方式调取通用行情接口。用户可以访问Tushare的Github，查看源代码完成类似功能。
 https://tushare.pro/document/2?doc_id=109

**Comment by uiosun** [comment]
Right，最近有空实现它吗？

**Comment by uiosun** [comment]
以及，我能提一个 PR 吗？我新增了一些接口

**Comment by yushikuann** [comment]
我最近没在研究这个，token 也过期了，你可以实现一下，但是建议做数据本地存储，分钟级数据量还是挺大的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yushikuann/go-tushare-sdk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月9日(星期四) 下午2:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yushikuann/go-tushare-sdk] 分钟线行情数据能用 Golang 拉取吗？ (Issue #1)





 
Right，最近有空实现它吗？

**Comment by yushikuann** [comment]
可以




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yushikuann/go-tushare-sdk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月9日(星期四) 下午2:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yushikuann/go-tushare-sdk] 分钟线行情数据能用 Golang 拉取吗？ (Issue #1)





 
以及，我能提一个 PR 吗？我新增了一些接口

**Comment by uiosun** [comment]
遇到一个问题：https://github.com/waditu/tushare/blob/093856995af0811d3ebbe8c179b8febf4ae706f0/tushare/pro/data_pro.py#L34

这里似乎没有分钟线的实现，文档上说参考源码，我该怎么找源码呢？

**Comment by uiosun** [comment]
PR merged.
